## WARMUPS

In [23]:
import numpy as np

In [ ]:
def w1(X):
    """
    Input:
    - X: A numpy array

    Returns:
    - A matrix Y such that Y[i, j] = X[i, j] * 10 + 100

    Hint: Trust that numpy will do the right thing

    *** AKA element-wise operations through broadcasting. so regardless of size X[i,j], each element is multiplied by 10 and adds 100 
    """
    return X * 10 + 100

In [ ]:
def w2(X, Y):
    """
    Inputs:
    - X: A numpy array of shape (N, N)
    - Y: A numpy array of shape (N, N)

    Returns:
    A numpy array Z such that Z[i, j] = X[i, j] + 10 * Y[i, j]

    Hint: Trust that numpy will do the right thing

    *** Same concept here as Y is multiplied element-wise by 10 and then added to X via normal linalg processes as they are the same size
    """
    return X + 10 * Y

In [ ]:
def w3(X, Y):
    """
    Inputs:
    - X: A numpy array of shape (N, N)
    - Y: A numpy array of shape (N, N)

    Returns:
    A numpy array Z such that Z[i, j] = X[i, j] * Y[i, j] - 10

    Hint: By analogy to +, * will do the same thing
    """
    return X * Y - 10

In [ ]:
def w4(X, Y):
    """
    Inputs:
    - X: Numpy array of shape (N, N)
    - Y: Numpy array of shape (N, N)

    Returns:
    A numpy array giving the matrix product X times Y

    Hint: 
    1. Be careful! There are different variants of *, @, dot
    2.  a = [[1,2],
             [1,2]]
        b = [[2,2],
             [3,3]]
        a * b = [[2,4],
                 [3,6]]
    Is this matrix multiplication?

    Matrix product = X @ Y = np.matmul
    """
    return X @ Y

In [ ]:
def w5(X):
    """
    Inputs:
    - X: A numpy array of shape (N, N) of floating point numbers

    Returns:
    A numpy array with the same data as X, but cast to 32-bit integers

    Hint: Check .astype() !
    
    int_array = float_array.astype(np.int32) defaul copies one array to a new casted array

    which is the same as....

    int_array = np.array(x, dtype=int32)

    BUT astype is memory efficient if cast to the original variable
    """
    return X.astype(np.int32)

In [ ]:
def w6(X, Y):
    """
    Inputs:
    - X: A numpy array of shape (N,) of integers
    - Y: A numpy array of shape (N,) of integers

    Returns:
    A numpy array Z such that Z[i] = float(X[i]) / float(Y[i])

    **** To handle division where Y = 0
    np.divide(X.astype(np.float64), Y.astype(np.float64), out=np.zeros_like(X, dtype=np.float64), where=Y!=0)
    
    """
    return X.astype(np.float64)/Y.astype(np.float64)


In [ ]:
def w7(X):
    """
    Inputs:
    - X: A numpy array of shape (N, M)

    Returns:
    - A numpy array Y of shape (N * M, 1) containing the entries of X in row
      order. That is, X[i, j] = Y[i * M + j, 0]

    Hint:
    1) np.reshape
    2) You can specify an unknown dimension as -1

    *** aka, you could use X.reshape(-1, 1) where numpy would see -1 as an unknown shape and calculate the shape as necessary to meet the (,1) demand 
    """
    n,m = np.shape(X)
    new = np.reshape(X,(n*m, 1))
    return new

In [ ]:
def w8(N):
    """
    Inputs:
    - N: An integer

    Returns:
    A numpy array of shape (N, 2N)

    Hint: The error "data type not understood" means you probably called
    np.ones or np.zeros with two arguments, instead of a tuple for the shape
    """
    return np.ones((N,2*N))

In [ ]:
def w9(X):
    """
    Inputs:
    - X: A numpy array of shape (N, M) where each entry is between 0 and 1

    Returns:
    A numpy array Y where Y[i, j] = True if X[i, j] > 0.5

    Hint: Try boolean array indexing
    """
    return X > 0.5

In [ ]:
def w10(N):
    """
    Inputs:
    - N: An integer

    Returns:
    A numpy array X of shape (N,) such that X[i] = i

    Hint: np.arange
    """
    return np.arange(N)

In [ ]:
def w11(A, v):
    """
    Inputs:
    - A: A numpy array of shape (N, F)
    - v: A numpy array of shape (F, 1)

    Returns:
    Numpy array of shape (N, 1) giving the matrix-vector product Av
    """
    return A.dot(v)

In [ ]:
def w12(A, v):
    """
    Inputs:
    - A: A numpy array of shape (N, N), of full rank
    - v: A numpy array of shape (N, 1)

    Returns:
    Numpy array of shape (N, 1) giving the matrix-vector product of the inverse
    of A and v: A^-1 v

    *** Full rank means invertible and is computed like so np.linalg.inv(A).

    Or np.linalg.solve(A, v) solves the equation Ax=v directly, which is more efficient and
    avoids numerical issues that might arise from computing the inverse explicitly.
    """
    return np.linalg.inv(A).dot(v)

In [ ]:
def w13(u, v):
    """
    Inputs:
    - u: A numpy array of shape (N, 1)
    - v: A numpy array of shape (N, 1)

    Returns:
    The inner product u^T v

    Hint: .T

    *** u.T.dot(v) would return a matrix of [1,1] when the below returns a scalar
    """
    return u.T @ (v)

In [ ]:
def w14(v):
    """
    Inputs:
    - v: A numpy array of shape (N, 1)

    Returns:
    The L2 norm of v: norm = (sum_i^N v[i]^2)^(1/2)
    You MAY NOT use np.linalg.norm

    *** Equation read as:
    square root of (the sum from i to N of each element of the vector squared)
    or sqrt(SUM from i to N of V[i] squared)
    """
    return np.sqrt(np.sum(v**2))

In [ ]:
def w15(X, i):
    """
    Inputs:
    - X: A numpy array of shape (N, M)
    - i: An integer in the range 0 <= i < N

    Returns:
    Numpy array of shape (M,) giving the ith row of X

    *** Stupid little way of saying, give me the ith row of X which will already be of the shape (M,)
    """
    return X[i]

In [ ]:
def w16(X):
    """
    Inputs:
    - X: A numpy array of shape (N, M)

    Returns:
    The sum of all entries in X

    Hint: np.sum
    """
    return np.sum(X)

In [ ]:
def w17(X):
    """
    Inputs:
    - X: A numpy array of shape (N, M)

    Returns:
    A numpy array S of shape (N,) where S[i] is the sum of row i of X

    Hint: np.sum has an optional "axis" argument

    *** Basically means sum across the columns which will produce S of shape(N,) where any given value is the sum of that rows columns
    The axis=1 argument tells NumPy to sum along columns, meaning that for each row i  
    i, the sum of all columns is calculated.
    This results in an array of shape (N,), which matches the expected output.
    """
    return np.sum(X, axis=1)

In [ ]:
def w18(X):
    """
    Inputs:
    - X: A numpy array of shape (N, M)

    Returns:
    A numpy array S of shape (M,) where S[j] is the sum of column j of X

    Hint: Same as above
    """
    return np.sum(X, axis=0)

In [ ]:
def w19(X):
    """
    Inputs:
    - X: A numpy array of shape (N, M)

    Returns:
    A numpy array S of shape (N, 1) where S[i, 0] is the sum of row i of X

    Hint: np.sum has an optional "keepdims" argument

    *** keepdims=True simply makes it (N,1) for a 2D answer rather than (N,)
    """
    return np.sum(X, axis=1, keepdims=True)

In [ ]:
def w20(X):
    """
    Inputs:
    - X: A numpy array of shape (N, M)

    Returns:
    A numpy array S of shape (N, 1) where S[i] is the L2 norm of row i of X
    """

    return np.sqrt(np.sum(X**2, axis=1, keepdims=True))

## TESTS

In [25]:
import numpy as np

a = np.array([[1,2,3]])
b = np.array([[4,5,6]])
c = np.array([[0,1,0]])

array_list1 = [a,b,c]

In [26]:

def t1(L):
    """
    Inputs:
    - L: A list of M numpy arrays, each of shape (1, N)

    Returns:
    A numpy array of shape (M, N) giving all inputs stacked together

    Par: 1 line
    Instructor: 1 line

    Hint: vstack/hstack/dstack, no for loop
    This is equivalent to concatenation along the first axis after 1-D arrays of shape (N,) have been reshaped to (1,N). Rebuilds arrays divided by vsplit.
    """

    return np.vstack(L)

print(t1(array_list1))



[[1 2 3]
 [4 5 6]
 [0 1 0]]


In [27]:
def t2(X):
    """
    Inputs:
    - X: A numpy array of shape (N, N)

    Returns:
    Numpy array of shape (N,) giving the eigenvector corresponding to the
    smallest eigenvalue of X

    Par: 5 lines
    Instructor: 3 lines

    Hints:
    1) np.linalg.eig
    2) np.argmin
    3) Watch rows and columns!
    """

    eig_vals, eig_vecs = np.linalg.eig(X) # returns an Eig object of ([eigenvalues], [eigenvectors])
    eig_val_min = np.argmin(eig_vals) # selects the INDEX of the smallest argument in the 1D array of Eigenvalues
    '''
    Eigenvectors is an (N,N) matrix where each column (,n) is an eigenvector rather than the rows
    eig_vecs[eig_val_min] returns the row which is incorrect while eig_vecs[: , eig_val_min] returns the column
    '''

    # Use the index of the minimum to return the corresponding eigenvector
    return eig_vecs[: ,eig_val_min]

print(t2(t1(array_list1)))

[ 0.65207662-0.j         -0.07535414+0.50288247j -0.31252866-0.46749641j]
